# Default values for dnsmasq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  tags:
    dnsmasq: kolla/ubuntu-binary-dnsmasq:4.0.6
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    image_repo_sync: docker.io/docker:17.07.0
  pull_policy: IfNotPresent
  local_registry:
    active: true
    exclude:
      - dep_check
      - image_repo_sync

nameOverride: ""
fullnameOverride: ""

labels:
  server:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

service:
  type: ClusterIP
  port: 67
  targetPort: 6767
  clusterIP: None
  protocol: UDP

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

network_policy:
  dnsmasq:
    ingress:
      - from:
        - podSelector:
            matchLabels:
              application: grafana
        - podSelector:
            matchLabels:
              application: mariadb
        ports:
        - protocol: UDP
          port: 67

#network_policy:
#  dnsmasq:
#    ingress:
#      - {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

conf:
  dnsmasq: |
    strict-order
    #user=libvirt-dnsmasq
    pid-file=/var/run/vbmc-ironic/dnsmasq.pid
    except-interface=lo
    except-interface=virbr0
    bind-dynamic
    interface=br-simulator
    dhcp-range=192.168.90.100,192.168.90.254,12h
    dhcp-no-override
    dhcp-authoritative
    dhcp-lease-max=253
    # Boot for Etherboot gPXE. The idea is to send two different
    # filenames, the first loads gPXE, and the second tells gPXE what to
    # load. The dhcp-match sets the gpxe tag for requests from gPXE.
    dhcp-userclass=set:gpxe,"gPXE"
    dhcp-boot=tag:gpxe,/ipxe.pxe
    dhcp-match=set:ipxe,175 # iPXE sends a 175 option.
    dhcp-boot=tag:ipxe,http://192.168.10.7:8080/boot.ipxe
    dhcp-hostsfile=/etc/dnsmasq.d/dnsmasq.hostsfile
    addn-hosts=/etc/dnsmasq.d/dnsmasq.addnhosts
  hostsfile: ""
  addnhosts: ""

manifests:
  configmap_etc: true
  service_dnsmasq: false
  deployment: true
