{{- if .Values.manifests.deployment }}                                                                                                                                                                                                       
{{- $envAll := . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dnsmasq.fullname" . }}
  labels:
{{ tuple $envAll "dnsmasq" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ tuple $envAll "dnsmasq" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "dnsmasq" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.images.tags.dnsmasq }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
            privileged: true
          command:
            - /usr/sbin/dnsmasq
            - "--user=root"
            - "-d"
            - "--log-dhcp"
#          ports:
#            - name: dnsmasq
#              containerPort: 6767
#              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
#          env:
#            - name: KOLLA_CONFIG_STRATEGY
#              value: COPY_ALWAYS
#            - name: KOLLA_CONFIG
#              value: '{"command": "/usr/sbin/dnsmasq"}'
          volumeMounts:
            - name: dnsmasq-etc
              mountPath: /etc/dnsmasq.conf
              subPath: dnsmasq.conf
              readOnly: true
            - name: dnsmasq-etc
              mountPath: /etc/dnsmasq.d/dnsmasq.hostsfile
              subPath: dnsmasq.hostsfile
              readOnly: true
            - name: dnsmasq-etc
              mountPath: /etc/dnsmasq.d/dnsmasq.addnhosts
              subPath: dnsmasq.addnhosts
              readOnly: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: dnsmasq-etc
          secret:
            secretName: dnsmasq-etc
            defaultMode: 0444
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}


{{- end }}
