{{/*
Copyright 2018 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.deployment }}
{{- $envAll := . }}

{{- $serviceAccountName := printf "%s-%s" $envAll.Release.Name "dnsmasq" }}
{{ tuple $envAll "dnsmasq" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $envAll.Release.Namespace }}
  labels:
{{ tuple $envAll "dnsmasq" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ tuple $envAll "dnsmasq" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "dnsmasq" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      initContainers:
        - name: dnsmasq-set-pxe-http
{{ tuple $envAll "dnsmasq" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.dnsmasq| include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
            - name: PROVISIONER_INTERFACE
              value: {{ .Values.network.pxe.device }}
          command:
            - /tmp/dnsmasq-set-pxe-http.sh
          volumeMounts:
            - name: dnsmasq-bin
              mountPath: /tmp/dnsmasq-set-pxe-http.sh
              subPath: dnsmasq-set-pxe-http.sh
              readOnly: true
            - name: dnsmasq-etc
              mountPath: /etc/dnsmasq.conf
              subPath: dnsmasq.conf
              readOnly: true
            - name: pod-shared
              mountPath: /tmp/pod-shared
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.images.tags.dnsmasq }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          serviceAccountName: {{ $serviceAccountName }}
          securityContext:
            privileged: true
          command:
            - /tmp/dnsmasq.sh
          volumeMounts:
            - name: dnsmasq-bin
              mountPath: /tmp/dnsmasq.sh
              subPath: dnsmasq.sh
              readOnly: true
            - name: pod-shared
              mountPath: /tmp/pod-shared
              readOnly: true
            - name: dnsmasq-etc
              mountPath: /etc/dnsmasq.d/dnsmasq.hostsfile
              subPath: dnsmasq.hostsfile
              readOnly: true
            - name: dnsmasq-etc
              mountPath: /etc/dnsmasq.d/dnsmasq.addnhosts
              subPath: dnsmasq.addnhosts
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: dnsmasq-etc
          secret:
            secretName: dnsmasq-etc
            defaultMode: 0444
        - name: pod-shared
          emptyDir: {}
        - name: dnsmasq-bin
          configMap:
            name: dnsmasq-bin
            defaultMode: 0555
      nodeSelector:
        {{ .Values.labels.server.node_selector_key }}: {{ .Values.labels.server.node_selector_value | quote }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

{{- end }}
