{{- if .Values.manifests.service_dnsmasq -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnsmasq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dnsmasq.name" . }}
    helm.sh/chart: {{ include "dnsmasq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- with .Values.service.type }}
  type: {{ . }}
  {{- end }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: dnsmasq
  selector:
    app.kubernetes.io/name: {{ include "dnsmasq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- end }}
